### ISSUE TITLE
rlimits issue

### ISSUE THREAD

**Issue by paboum** [ernestwisniewski/kbin#8]
`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown`
casued by these lines of `docker-compose.yml` for elasticsearch:
```
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

```
for some platforms, possibly related to Kubernetes or whatever my cloud vendor uses.
